# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build & Test

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    strategy:
      matrix:
        platform: [ ubuntu-22.04, macos-13, windows-2022 ]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.1

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
